CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGSERIAL PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    START_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    END_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRICE NUMERIC(19, 2) NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,

    CONSTRAINT fk_price_brand FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
    CONSTRAINT fk_price_product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);
